### ISSUE TITLE
Flat: Can't Close Vector Path

### ISSUE THREAD

**Issue by michielkauwatjoe** [PageBot/PageBot#183]
Happens in PDF and SVG, not PNG;
```
Traceback (most recent call last):
  File "./DrawQuadraticGlyph.py", line 290, in <module>
    draw(context)
  File "./DrawQuadraticGlyph.py", line 285, in draw
    context.saveImage(path)
  File "/Users/michiel/Code/PageBot/Lib/pagebot/contexts/flat/flatcontext.py", line 187, in saveDocument
    self.doc.pdf(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat/document.py", line 81, in pdf
    data = pdfserialize(self, compress, bleed, cropmarks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat/pdf.py", line 408, in serialize
    item.pdf(page.height, state, resources) for item in page.items)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat/pdf.py", line 408, in <genexpr>
    item.pdf(page.height, state, resources) for item in page.items)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat/shape.py", line 457, in pdf
    shape = self.item.pdf(self.k, self.x, height-self.y)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flat/shape.py", line 429, in pdf
    return b' '.join(fragments)
TypeError: sequence item 5: expected a bytes-like object, str found
```

**Comment by michielkauwatjoe** [comment]
Fixed by  https://github.com/xxyxyz/flat/pull/8
