### ISSUE TITLE
No module named 'flat'

### ISSUE THREAD

**Issue by frankrolf** [PageBot/PageBot#192]
I installed PageBot via pip, and tried to run the basic example (unsuccessfully):

```
Traceback (most recent call last):
  File "pb.py", line 1, in <module>
    from pagebot.document import Document
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pagebot/__init__.py", line 21, in <module>
    from pagebot.contexts import getContext as getPlatformContext
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pagebot/contexts/__init__.py", line 19, in <module>
    from pagebot.contexts.flatcontext.flatcontext import FlatContext
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pagebot/contexts/flatcontext/flatcontext.py", line 21, in <module>
    from flat import rgb
ModuleNotFoundError: No module named 'flat'
```

**Comment by michielkauwatjoe** [comment]
@frankrolf @petrvanblokland Hi,

Flat is a dependency that is in the requirements;

    https://github.com/PageBot/PageBot/blob/master/requirements.txt

A couple of questions; do you know if it installed together with PageBot, or did you already have it on your system? Which Python are you using? Could you check if you're able to import flat itself?

Thanks,

Michiel.

**Comment by frankrolf** [comment]
I am using Python 3.7.4 installed via `pyenv`.
As far as I can tell, `flat` simply has not been installed as expected:

```
[~] pip install pagebot                                                           22:29:56
Collecting pagebot
  Downloading https://files.pythonhosted.org/packages/ce/b5/85ecaa46445effb02ea7e127aae95136a813bd44565d7a6f48e14989d64e/pagebot-0.9.3-py3-none-any.whl (28.5MB)
     |████████████████████████████████| 28.5MB 655kB/s
Collecting libsass
  Downloading https://files.pythonhosted.org/packages/66/0c/6c9194d0d1d84d56bee899d18bb9d940725e3d80cbc9048b00b5ff96afb1/libsass-0.19.4-cp37-cp37m-macosx_10_14_x86_64.whl (984kB)
     |████████████████████████████████| 993kB 834kB/s
Collecting svgwrite
  Downloading https://files.pythonhosted.org/packages/4f/2e/f36cfec1da6162055b884e6366074cff18475a9538559ceae0c0bc58e186/svgwrite-1.3.1-py2.py3-none-any.whl (67kB)
     |████████████████████████████████| 71kB 1.5MB/s
Requirement already satisfied: fontTools in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from pagebot) (4.0.1)
Collecting markdown
  Downloading https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl (87kB)
     |████████████████████████████████| 92kB 1.3MB/s
Collecting SimpleIDML
  Downloading https://files.pythonhosted.org/packages/88/51/c33a0934a7a0896842e3e27fb9057dc22d16fa54a8a54ecad295a1f65d72/SimpleIDML-1.0.6.tar.gz (4.8MB)
     |████████████████████████████████| 4.8MB 836kB/s
Collecting tornado
  Downloading https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz (482kB)
     |████████████████████████████████| 491kB 1.1MB/s
Requirement already satisfied: booleanOperations in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from pagebot) (0.8.2)
Requirement already satisfied: six in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from libsass->pagebot) (1.12.0)
Collecting pyparsing>=2.0.1
  Downloading https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl (67kB)
     |████████████████████████████████| 71kB 1.2MB/s
Requirement already satisfied: setuptools>=36 in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from markdown->pagebot) (40.8.0)
Collecting future
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
     |████████████████████████████████| 829kB 1.5MB/s
Requirement already satisfied: lxml in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from SimpleIDML->pagebot) (4.4.1)
Collecting suds-py3
  Downloading https://files.pythonhosted.org/packages/87/f0/471d57cf47b1fddd0a3b6f1b3e9843e90494c8986e17a27cbc64e7d4fc56/suds_py3-1.3.4.0-py3-none-any.whl (297kB)
     |████████████████████████████████| 307kB 1.2MB/s
Requirement already satisfied: pyclipper>=1.0.5 in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from booleanOperations->pagebot) (1.1.0.post1)
Building wheels for collected packages: SimpleIDML, tornado, future
  Building wheel for SimpleIDML (setup.py) ... done
  Created wheel for SimpleIDML: filename=SimpleIDML-1.0.6-cp37-none-any.whl size=48238 sha256=83f967da3ec995544f9d9f29012a34fe3fe71a1d019c13791f87eac2d4aa9759
  Stored in directory: /Users/fgriessh/Library/Caches/pip/wheels/41/a6/eb/2c0f5478190f48579985b4c03ccf2a5221c7212a5d6807e36a
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.0.3-cp37-cp37m-macosx_10_15_x86_64.whl size=412906 sha256=c041884b2e7a8d9e5d80938c546cba9bf9b2532c5b8eed4fa0f900654752fea4
  Stored in directory: /Users/fgriessh/Library/Caches/pip/wheels/84/bf/40/2f6ef700f48401ca40e5e3dd7d0e3c0a90e064897b7fe5fc08
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-cp37-none-any.whl size=491057 sha256=d4898d2b8c57c65ed323800caaa311aeb1f4db34fc62a4157b57187af887099c
  Stored in directory: /Users/fgriessh/Library/Caches/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
Successfully built SimpleIDML tornado future
Installing collected packages: libsass, pyparsing, svgwrite, markdown, future, suds-py3, SimpleIDML, tornado, pagebot
Successfully installed SimpleIDML-1.0.6 future-0.18.2 libsass-0.19.4 markdown-3.1.1 pagebot-0.9.3 pyparsing-2.4.6 suds-py3-1.3.4.0 svgwrite-1.3.1 tornado-6.0.3
```

**Comment by michielkauwatjoe** [comment]
@frankrolf Hm, seems I somehow commented the flat requirement in setup.py. I'll have to upload a new version of PageBot to PyPi; could you install flat separately for now? `pip install flat` should do the trick...

**Comment by frankrolf** [comment]
That did the trick! – plus one additional step:
`pip install pagebotcocoa`
