### ISSUE TITLE
Contributions & Dependencies: MarkDown Extensions

### ISSUE THREAD

**Issue by michielkauwatjoe** [PageBot/PageBot#217]
```
**********************************************************************
File "./typesetter.py", line 129, in __main__.Typesetter.__init__
Failed example:
    galley = ts.typesetMarkdown(mdText)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.Typesetter.__init__[12]>", line 1, in <module>
        galley = ts.typesetMarkdown(mdText)
      File "./typesetter.py", line 741, in typesetMarkdown
        fileName = self.markDown2XmlFile(tmpPath, mdText, mdExtensions)
      File "./typesetter.py", line 720, in markDown2XmlFile
        xmlBody = markdown.markdown(mdText, extensions=mdExtensions)
      File "/Users/michiel/VirtualEnvironments/pagebot/lib/python3.8/site-packages/markdown/core.py", line 387, in markdown
        return md.convert(text)
      File "/Users/michiel/VirtualEnvironments/pagebot/lib/python3.8/site-packages/markdown/core.py", line 268, in convert
        newRoot = treeprocessor.run(root)
      File "/Users/michiel/VirtualEnvironments/pagebot/lib/python3.8/site-packages/markdown/treeprocessors.py", line 370, in run
        self.__handleInline(text), child
      File "/Users/michiel/VirtualEnvironments/pagebot/lib/python3.8/site-packages/markdown/treeprocessors.py", line 131, in __handleInline
        self.inlinePatterns[patternIndex], data, patternIndex, startIndex
      File "/Users/michiel/VirtualEnvironments/pagebot/lib/python3.8/site-packages/markdown/util.py", line 311, in __getitem__
        self._sort()
      File "/Users/michiel/VirtualEnvironments/pagebot/lib/python3.8/site-packages/markdown/util.py", line 382, in _sort
        self._priority.sort(key=lambda item: item.priority, reverse=True)
    TypeError: '<' not supported between instances of 'str' and 'int'
**********************************************************************
```

**Comment by michielkauwatjoe** [comment]
Fixed, still need to check if priorities are correctly set.
